/**
 * Default destinations for the mileage tracker.
 * Users can override these with their own destinations via props or Settings.
 */

import type { Destination } from './types';

export const DEFAULT_DESTINATIONS: Destination[] = [
  {
    id: 'downtown',
    name: 'Downtown Charleston',
    subtitle: 'Networking + farmers mkt',
    defaultMiles: 10,
    type: 'Business',
    icon: 'building',
    color: '#5DCAA5',
    defaultNote: 'Networking at luxury stores, farmers market',
    category: 'Networking',
  },
  {
    id: 'downtown2',
    name: 'Downtown Trip #2',
    subtitle: 'Brand meeting / content',
    defaultMiles: 10,
    type: 'Business',
    icon: 'briefcase',
    color: '#5DCAA5',
    defaultNote: 'Brand deal meeting / content scouting',
    category: 'Networking',
  },
  {
    id: 'chase',
    name: 'Chase Bank',
    subtitle: 'Business banking',
    defaultMiles: 4,
    type: 'Business',
    icon: 'bank',
    color: '#85B7EB',
    defaultNote: 'Business account transaction',
    category: 'Banking',
  },
  {
    id: 'brandmgr',
    name: 'Brand Manager',
    subtitle: 'Meeting / contracts',
    defaultMiles: 6,
    type: 'Business',
    icon: 'handshake',
    color: '#85B7EB',
    defaultNote: 'Brand manager meeting - contracts/deals',
    category: 'Brand Manager',
  },
  {
    id: 'supplies',
    name: 'Supply Run',
    subtitle: 'B&N, wardrobe, shipping',
    defaultMiles: 6,
    type: 'Business',
    icon: 'bag',
    color: '#85B7EB',
    defaultNote: 'Content supplies pickup',
    category: 'Supply Run',
  },
  {
    id: 'summerville',
    name: 'Summerville Student',
    subtitle: 'Student mentorship',
    defaultMiles: 50,
    type: 'Business',
    icon: 'graduation',
    color: '#AFA9EC',
    defaultNote: 'Academy of Indigo Education - student mentorship',
    category: 'Student Visit',
  },
  {
    id: 'bookstore',
    name: 'Bookstore Pitch',
    subtitle: 'Book outreach',
    defaultMiles: 0,
    type: 'Business',
    icon: 'book',
    color: '#FAC775',
    defaultNote: 'Pitched book to store manager',
    category: 'Book Sales',
  },
  {
    id: 'filming',
    name: 'Content Filming',
    subtitle: 'On-location shoot',
    defaultMiles: 0,
    type: 'Business',
    icon: 'camera',
    color: '#F0997B',
    defaultNote: 'On-location content filming for TTC',
    category: 'Content Filming',
  },
  {
    id: 'gym',
    name: 'Gym',
    subtitle: 'Crunch Fitness',
    defaultMiles: 4.2,
    type: 'Personal',
    icon: 'dumbbell',
    color: '#909090',
    defaultNote: 'Personal workout',
    category: 'Gym',
  },
  {
    id: 'errands',
    name: 'Personal Errands',
    subtitle: 'Groceries, misc',
    defaultMiles: 0,
    type: 'Personal',
    icon: 'cart',
    color: '#909090',
    defaultNote: 'Personal errands',
    category: 'Personal',
  },
  {
    id: 'custom',
    name: 'Custom Trip',
    subtitle: 'Enter details',
    defaultMiles: 0,
    type: 'Business',
    icon: 'pin',
    color: '#85B7EB',
    defaultNote: '',
    category: 'Other',
  },
];
