/**
 * Default saved places for the mileage tracker.
 * Users can override these with their own places via props or Settings.
 * Addresses are placeholders — users should update them in Settings
 * and geocode to get GPS coordinates for auto-distance calculation.
 */

import type { Destination } from './types';

export const DEFAULT_DESTINATIONS: Destination[] = [
  {
    id: 'downtown',
    name: 'Downtown Office',
    subtitle: 'Client meetings + networking',
    type: 'Business',
    icon: 'building',
    color: '#5DCAA5',
    defaultNote: 'Client meeting / networking event',
    category: 'Networking',
    address: '',
  },
  {
    id: 'coworking',
    name: 'Coworking Space',
    subtitle: 'Remote work day',
    type: 'Business',
    icon: 'briefcase',
    color: '#5DCAA5',
    defaultNote: 'Working from coworking space',
    category: 'Networking',
    address: '',
  },
  {
    id: 'bank',
    name: 'Bank',
    subtitle: 'Business banking',
    type: 'Business',
    icon: 'bank',
    color: '#85B7EB',
    defaultNote: 'Business account transaction',
    category: 'Banking',
    address: '',
  },
  {
    id: 'client',
    name: 'Client Site',
    subtitle: 'On-site meeting',
    type: 'Business',
    icon: 'handshake',
    color: '#85B7EB',
    defaultNote: 'Client on-site meeting - project review',
    category: 'Client Visit',
    address: '',
  },
  {
    id: 'supplies',
    name: 'Supply Run',
    subtitle: 'Office supplies, shipping',
    type: 'Business',
    icon: 'bag',
    color: '#85B7EB',
    defaultNote: 'Business supplies pickup',
    category: 'Supply Run',
    address: '',
  },
  {
    id: 'conference',
    name: 'Conference',
    subtitle: 'Industry event',
    type: 'Business',
    icon: 'graduation',
    color: '#AFA9EC',
    defaultNote: 'Industry conference / professional development',
    category: 'Conference',
    address: '',
  },
  {
    id: 'postoffice',
    name: 'Post Office',
    subtitle: 'Shipping & mailing',
    type: 'Business',
    icon: 'book',
    color: '#FAC775',
    defaultNote: 'Business package shipping',
    category: 'Errands',
    address: '',
  },
  {
    id: 'jobsite',
    name: 'Job Site',
    subtitle: 'Field work',
    type: 'Business',
    icon: 'camera',
    color: '#F0997B',
    defaultNote: 'On-location field work',
    category: 'Field Work',
    address: '',
  },
  {
    id: 'gym',
    name: 'Gym',
    subtitle: 'Personal fitness',
    type: 'Personal',
    icon: 'dumbbell',
    color: '#909090',
    defaultNote: 'Personal workout',
    category: 'Gym',
    address: '',
  },
  {
    id: 'errands',
    name: 'Personal Errands',
    subtitle: 'Groceries, misc',
    type: 'Personal',
    icon: 'cart',
    color: '#909090',
    defaultNote: 'Personal errands',
    category: 'Personal',
    address: '',
  },
  {
    id: 'custom',
    name: 'Custom Trip',
    subtitle: 'Enter details',
    type: 'Business',
    icon: 'pin',
    color: '#85B7EB',
    defaultNote: '',
    category: 'Other',
    address: '',
  },
];
